version: "3"
services:
  spads:
    image: public.ecr.aws/w6o6x2e9/spads
    env_file:
      - .env
    build:
      context: .
      args:
        SPADS_PLUGINS: "AutoRegister;ClusterManager;JsonStatus;InGameMute;Resign"
    network_mode: 'host'
    environment:
      - "SPRING_DATADIR=/spring-data"
      - "SPRING_WRITEDIR=/spring-data"
      - "SPADS_ARGS=--tls-cert-trust"
    volumes:
      - spring_data:/spring-data
      - spads_cache:/opt/spads/var
      - spring_engines:/spring-engines

  games-updater:
    command: /usr/bin/sync-all.sh
    image: public.ecr.aws/w6o6x2e9/spads-services:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.services
    volumes:
      - spring_data:/spring-data
      - spring_engines:/spring-engines

volumes:
  spring_data:
  spring_engines:
  spads_cache:
